#ifndef KEYMAP_CONFIG_H
#define KEYMAP_CONFIG_H

// RGB MATRIX CONFIG
#define RGB_MATRIX_SLEEP
#define RGB_MATRIX_DEFAULT_HUE 180

#define ENABLE_RGB_MATRIX_TYPING_HEATMAP

#endif // !USERSPACE_CONFIG_H

